-- ============================================================
-- Carga dos projetos reais - 29 marcas, 156 imagens
-- Gerado a partir da pasta de mockups, com curadoria por segmento.
--
-- Aplicar:  npm run cf:d1:projects        (producao)
--           npm run cf:d1:projects:local  (local)
-- ============================================================

DELETE FROM project_images;
DELETE FROM projects;

INSERT INTO projects
  (slug, title, tag, category, year, client, summary, body, cover, featured, position, published)
VALUES
  ('scope','Scope','Branding / Inteligência Geoespacial','Branding','2026','Scope','Identidade para uma empresa de inteligência geoespacial.','Dado de campo só vira decisão quando alguém confia nele. A Scope trabalha com levantamento e análise geoespacial para setores que não podem errar de medida, energia, infraestrutura, agro. A marca precisava carregar essa precisão sem virar fria: o verde de instrumento de campo, a malha triangular que remete a triangulação topográfica e uma tipografia que se sustenta tanto na tela do escritório quanto no colete de quem está no meio do nada levantando ponto.','images/work/scope/01.webp',1,1,1),
  ('fiveasy','Fiveasy','Branding / Produto Digital','Branding','2026','Fiveasy','Marca de uma plataforma que simplifica processo complicado.','O nome já entrega a promessa: transformar cinco passos em um. A Fiveasy nasceu para tirar burocracia do caminho de quem só quer resolver, e a identidade tinha que provar isso antes da primeira tela, verde-menta sobre preto, símbolo que é ao mesmo tempo um F e uma seta de avanço, e um sistema que respira. Nada de ornamento: se a marca parecer complicada, a promessa cai.','images/work/fiveasy/01.webp',1,2,1),
  ('bilhetou','Bilhetou','Branding / Plataforma de Ingressos','Branding','2025','Bilhetou','Identidade para uma plataforma de venda de ingressos.','Comprar ingresso é o momento mais frágil da jornada de um evento: é onde o público desiste. A Bilhetou se posiciona como a plataforma que não atrapalha, e a marca foi construída para transmitir segurança sem perder o calor de quem está prestes a ver um show. O laranja carrega a expectativa, o preto sustenta a confiança e o símbolo é um B que também é um ingresso destacado.','images/work/bilhetou/01.webp',1,3,1),
  ('atrai','Atrai','Branding / Marketing e Growth','Branding','2026','Atrai','Marca para uma operação de aquisição e crescimento.','Atrair é o começo de tudo, mas virou palavra gasta no mercado de marketing. A saída foi fugir do clichê visual do setor, nada de gradiente colorido e ícone de foguete. A identidade se sustenta em preto e branco, com um símbolo de três formas convergindo para o mesmo ponto: o movimento de atração, resolvido em geometria. Marca sóbria em um mercado barulhento chama mais atenção do que mais barulho.','images/work/atrai/01.webp',1,4,1),
  ('agil','Ágil','Branding / Logística','Branding','2025','Ágil','Identidade para uma operação logística.','Em logística ninguém elogia quando dá certo, só reclama quando atrasa. A Ágil queria uma marca que transmitisse constância antes de velocidade, porque é isso que o cliente realmente compra. O azul institucional dá a base de confiança, o símbolo sugere um avião de papel em movimento e o sistema foi desenhado para funcionar do cartão de visita à lateral do veículo sem perder legibilidade a 80 km/h.','images/work/agil/01.webp',1,5,1),
  ('spark','Spark','Branding / Energia e Inovação','Branding','2026','Spark','Marca para uma empresa de energia e inovação.','Faísca é o instante antes da coisa acontecer, e era exatamente esse o posicionamento: a Spark não vende energia, vende o começo de algo. A identidade traduz isso num raio que também é a letra do nome, aplicado em luz sobre concreto. O laranja aquece um setor historicamente frio e a arquitetura da marca foi pensada para brilhar de verdade: quase toda aplicação prevê iluminação real, não simulada.','images/work/spark/01.webp',1,6,1),
  ('evolve-sales','Evolve Sales','Branding / Consultoria de Vendas','Branding','2025','Evolve Sales','Identidade para uma consultoria de performance comercial.','Consultoria de vendas vive um paradoxo: precisa parecer agressiva o suficiente para gerar resultado e séria o suficiente para entrar em conselho de administração. A Evolve Sales resolveu isso na proporção, vermelho contido dentro de uma estrutura branca e rígida. O símbolo sugere uma seta ascendente cortada em planos, a ideia de evolução por etapas, que é justamente como a metodologia deles funciona.','images/work/evolve-sales/01.webp',1,7,1),
  ('carsure','Carsure','Branding / Seguros','Branding','2025','Carsure','Manual de marca para uma seguradora automotiva.','Seguro é um produto que só é lembrado no pior dia da vida do cliente. A Carsure quis se posicionar como parceira antes do acidente, não como burocracia depois dele. O sistema visual foi construído em torno de uma forma de escudo abstrata, sem o clichê de proteção literal, e um azul que atravessa do institucional ao digital. O manual definiu regras rígidas de aplicação justamente para a marca chegar igual em toda ponta de atendimento.','images/work/carsure/01.webp',1,8,1),
  ('total-led','Total Led','Branding / Iluminação Industrial','Branding','2025','Total Led','Identidade para uma indústria de iluminação LED.','Vender iluminação de alto padrão para galpão e indústria é vender cálculo, garantia e durabilidade, não beleza. A Total Led precisava de uma marca que abrisse porta em compra técnica e ainda funcionasse no showroom. O amarelo âmbar puxa a temperatura da luz que eles fabricam, o traço é industrial sem ser pesado, e a identidade foi testada primeiro nos lugares mais hostis: baú de caminhão, estande de feira e catálogo técnico.','images/work/total-led/01.webp',0,9,1),
  ('gbs','GBS','Branding / Distribuição','Branding','2025','GBS','Marca para uma distribuidora com operação nacional.','Distribuidora compete por prazo, preço e presença, e presença é onde a marca entra. A GBS precisava ser reconhecida na estrada antes de ser lida, então o sistema nasceu pela aplicação maior: a lateral do caminhão. Verde e laranja em blocos de alto contraste, mensagem comercial integrada à identidade e uma hierarquia que funciona a 100 metros de distância. Do veículo, o sistema desceu para o digital, e não o contrário.','images/work/gbs/01.webp',0,10,1),
  ('vivamente','Vivamente','Branding / Saúde e Bem-estar','Branding','2026','Vivamente','Identidade para uma linha de suplementos em sachê.','A prateleira de suplemento é uma guerra de promessa exagerada. A Vivamente entrou pelo caminho oposto: verde claro, muito espaço em branco e uma comunicação que fala de rotina, não de milagre. A embalagem foi desenhada para o gesto real do produto, o sachê que se abre no meio do dia, e o sistema mantém a mesma calma do farmacêutico ao anúncio, porque a marca vende constância, não empolgação.','images/work/vivamente/01.webp',0,11,1),
  ('dani-molino','Dani Molino','Branding / Marca Pessoal','Branding','2026','Dani Molino','Identidade pessoal para uma profissional da saúde.','Marca pessoal em saúde caminha numa linha fina: precisa ser acolhedora sem parecer amadora, e técnica sem virar hospital. O monograma DM resolve isso em traço fino e dourado, apoiado num rosa que aparece em bloco, nunca em decoração. O sistema foi pensado para o consultório real, jaleco, papelaria, material de acompanhamento, porque é ali que a paciente decide se volta ou não.','images/work/dani-molino/01.webp',0,12,1),
  ('memorias-que-ficam','Memórias que Ficam','Branding / Produto Editorial','Branding','2025','Memórias que Ficam','Marca de um produto editorial sobre memória.','O tema é delicado: memória, o que se perde e o que fica. A identidade evita tanto o tom clínico quanto o excessivamente sentimental, o cérebro aparece em ilustração suave, quase gráfica, e o rosa carrega afeto sem infantilizar. A tipografia mistura serifa e manuscrito para sugerir o gesto de escrever à mão, que é a origem do próprio produto.','images/work/memorias-que-ficam/01.webp',0,13,1),
  ('post-stenci','Post Stenci','Social Media / Saúde','Social Media','2025','Stenci','Sistema de peças para uma solução de agendamento em clínicas.','O produto resolve uma dor específica: paciente que não confirma consulta e horário que fica vago. A comunicação precisava explicar isso rápido, para gestor de clínica que lê no intervalo entre atendimentos. O sistema usa o verde do WhatsApp como ponte de reconhecimento imediato, o azul da saúde como base institucional, e cada peça foi montada como um argumento fechado, dá para entender a oferta em uma imagem só.','images/work/post-stenci/01.webp',0,14,1),
  ('applespace','AppleSpace','Branding / Varejo de Tecnologia','Branding','2026','AppleSpace','Identidade para uma loja de produtos e serviços Apple.','Loja autorizada vive à sombra da marca que revende. O desafio era construir presença própria sem competir com o ecossistema Apple nem parecer imitação barata dele. A saída foi o nome: espaço. A identidade trabalha com um símbolo orbital, preto profundo e muito respiro, a mesma gramática de silêncio visual, mas com personalidade autoral suficiente para a loja ser lembrada pelo nome dela.','images/work/applespace/01.webp',0,15,1),
  ('lava-jato','Lava Jato','Branding / Estética Automotiva','Branding','2025','Lava Jato','Marca para uma operação de estética automotiva.','Serviço de bairro compete no impulso: o motorista decide em três segundos, passando de carro. A identidade foi construída para esse tempo, azul e amarelo em contraste máximo, mascote que humaniza o serviço e uma promessa direta na fachada. O sistema desce para o digital com a mesma clareza, porque a segunda decisão do cliente acontece no celular, no agendamento.','images/work/lava-jato/01.webp',0,16,1),
  ('luz-casting','Luz Casting','Branding / Audiovisual','Branding','2025','Luz Casting','Identidade para uma agência de casting.','Agência de casting trabalha entre dois públicos opostos: o talento, que quer ser visto, e a produção, que quer resolver rápido. A marca precisava servir aos dois. A cadeira de diretor virou símbolo, objeto que todo mundo do meio reconhece, e o amarelo funciona como luz de set, sinalizando movimento e seleção. Sóbria para o cliente, aspiracional para quem quer entrar.','images/work/luz-casting/01.webp',0,17,1),
  ('jusp-2025','JUSP 2025','Direção Criativa / Evento','Direção Criativa','2025','JUSP','Identidade da terceira edição de um evento esportivo.','Identidade de evento tem vida curta e precisa ser memorável na primeira exposição. A da terceira edição do JUSP foi construída como um brasão: montanha, água e fogo dentro de um selo, elementos que remetem ao lugar da competição e ao espírito da disputa. Formato de emblema porque a aplicação principal não é digital, é o uniforme que o participante leva para casa e continua usando depois.','images/work/jusp-2025/01.webp',0,18,1),
  ('shinkairace','Shinkai Race','Direção Criativa / Automobilismo','Direção Criativa','2026','Shinkai Race','Marca para uma operação de automobilismo.','Velocidade é o clichê mais óbvio do setor, e o mais difícil de fazer bem. A saída foi não desenhar movimento, e sim rastro: o vermelho se dispersa em partículas atrás da marca, sugerindo o que ficou para trás em vez do que está indo. O nome mistura referência japonesa e vocabulário de corrida, e o sistema foi feito para sobreviver ao ambiente mais hostil que existe para uma marca, a lataria de um carro em movimento.','images/work/shinkairace/01.webp',0,19,1),
  ('twinkfighter','Twinkfighter','Direção Criativa / Esports','Direção Criativa','2026','Twinkfighter','Identidade para uma marca de esports.','Esports é entretenimento antes de ser esporte, e a marca vive de palco. O símbolo foi desenhado como monograma angular, que funciona tanto em overlay de transmissão quanto em estrutura física de arena. O vermelho não é decoração: é a cor que atravessa fumaça e luz de show sem sumir. Todo o sistema foi validado no cenário mais difícil, o palco, e só depois adaptado para tela.','images/work/twinkfighter/01.webp',0,20,1),
  ('star-games','Star Games','Branding / Games','Branding','2025','Star Games','Marca para uma operação do mercado de games.','Roxo e estrela são lugar-comum em games, o trabalho foi usar os dois sem parecer genérico. A estrela virou forma recortada dentro de um escudo, criando um símbolo que funciona como ícone de app, como selo e como luz de parede. O sistema aposta em profundidade em vez de cor: quase toda aplicação prevê relevo, neon ou sombra, porque é assim que o público-alvo consome imagem.','images/work/star-games/01.webp',0,21,1),
  ('evo','EVO','Direção Criativa / Cultura Automotiva','Direção Criativa','2026','EVO','Identidade para uma marca da cultura automotiva japonesa.','A cultura JDM tem código próprio e detecta impostor de longe. A identidade foi construída de dentro da cultura, não sobre ela: dourado sobre azul-noite, referência ao Fuji, tipografia com peso de emblema de carro. O sistema aparece em couro, em papel texturizado e em adesivo, os três materiais que essa comunidade realmente usa, e evita qualquer estética esportiva ocidental.','images/work/evo/01.webp',0,22,1),
  ('grp-city','GRP City','Direção Criativa / Comunidade','Direção Criativa','2025','Gringolândia RP','Identidade para uma comunidade de roleplay.','Servidor de roleplay é cidade: tem regra, hierarquia e identidade própria. A marca precisava funcionar como bandeira de território, algo que o jogador quisesse vestir fora do jogo. A caveira coroada carrega o tom da comunidade, irreverente, urbana, um pouco fora da lei, e o sistema nasceu direto em vestuário, porque é ali que a lealdade do público se torna visível.','images/work/grp-city/01.webp',0,23,1),
  ('baixada','Baixada','Direção Criativa / Comunidade','Direção Criativa','2025','Baixada','Marca para uma comunidade urbana de roleplay.','O nome é território e o território é a linguagem. A identidade foi construída com o vocabulário da rua, neon, chuva, luz de poste, tipografia condensada de placa, para que o pertencimento fosse imediato para quem é de dentro. O laranja funciona como cor de sinalização urbana e o sistema se aplica melhor em ambiente físico simulado do que em fundo branco, porque a marca não vive em apresentação: vive na cidade.','images/work/baixada/01.webp',0,24,1),
  ('barra','Barra','Branding / Streetwear','Branding','2026','Barra','Identidade para uma marca de streetwear.','Streetwear se sustenta em wordmark, não em símbolo, a peça é a mídia. O logotipo foi desenhado em traço condensado com gradiente quente, pensado para ocupar a largura inteira do peito e ainda ser reconhecível espremido numa etiqueta. Sem símbolo auxiliar, sem versão alternativa: uma marca só, forte o suficiente para carregar a coleção sozinha.','images/work/barra/01.webp',0,25,1),
  ('acalmarsi','Acalmarsi','Branding / Vestuário e Causa','Branding','2025','Acalmarsi','Marca de vestuário com pauta de neurodiversidade.','Vestir uma causa é diferente de estampar uma causa. A Acalmarsi trabalha neurodiversidade sem tom de campanha e sem apelo, a peça precisa ser boa de usar mesmo para quem não conhece o tema. A paleta é quente e baixa em estímulo, coerente com o público que a marca representa, e a mensagem aparece em tipografia direta, sem ironia e sem pena.','images/work/acalmarsi/01.webp',0,26,1),
  ('nova','NOVA','Direção Criativa / Universo Digital','Direção Criativa','2026','NOVA','Manual de marca para um universo digital.','Marca de universo digital precisa de mais disciplina que marca de empresa, porque será aplicada por muita gente diferente e sem supervisão. O manual da NOVA definiu o essencial: roxo e ciano como par fixo, tratamento de luz obrigatório e regras claras de aplicação sobre imagem. O resultado é uma identidade que aguenta ser usada por terceiros sem se descaracterizar.','images/work/nova/01.webp',0,27,1),
  ('pousada-maya','Pousada Maya','Landing Page / Hospitalidade','Landing Page','2026','Pousada Maya','Página de conversão para uma pousada na Chapada dos Veadeiros.','Quem procura pousada na Chapada não está comprando quarto: está comprando descanso. A página foi escrita e desenhada nessa ordem, primeiro a sensação do lugar, depois a estrutura, e só no fim o preço. Tipografia serifada e fotografia com muito respiro para desacelerar a leitura, e um caminho único de reserva, sem distração. Menos oferta na tela, mais decisão.','images/work/pousada-maya/01.webp',0,28,1),
  ('lp-programmer','LP Programmer','Landing Page / Tecnologia','Landing Page','2026','LP Programmer','Página de conversão para uma operação de desenvolvimento.','Empresa de tecnologia costuma vender processo e esquecer de vender resultado. A página inverte: começa pelo problema do cliente, mostra a entrega e só depois explica o método. O visual escuro com acento ciano dá o repertório técnico que o público espera, mas a estrutura da página é comercial do início ao fim, cada bloco existe para tirar uma objeção do caminho.','images/work/lp-programmer/01.webp',0,29,1);

INSERT INTO project_images (project_id, key, alt, position) VALUES
  ((SELECT id FROM projects WHERE slug='scope'), 'images/work/scope/01.webp', 'Scope', 0),
  ((SELECT id FROM projects WHERE slug='scope'), 'images/work/scope/02.webp', 'Scope', 1),
  ((SELECT id FROM projects WHERE slug='scope'), 'images/work/scope/03.webp', 'Scope', 2),
  ((SELECT id FROM projects WHERE slug='scope'), 'images/work/scope/04.webp', 'Scope', 3),
  ((SELECT id FROM projects WHERE slug='scope'), 'images/work/scope/05.webp', 'Scope', 4),
  ((SELECT id FROM projects WHERE slug='fiveasy'), 'images/work/fiveasy/01.webp', 'Fiveasy', 0),
  ((SELECT id FROM projects WHERE slug='fiveasy'), 'images/work/fiveasy/02.webp', 'Fiveasy', 1),
  ((SELECT id FROM projects WHERE slug='fiveasy'), 'images/work/fiveasy/03.webp', 'Fiveasy', 2),
  ((SELECT id FROM projects WHERE slug='fiveasy'), 'images/work/fiveasy/04.webp', 'Fiveasy', 3),
  ((SELECT id FROM projects WHERE slug='fiveasy'), 'images/work/fiveasy/05.webp', 'Fiveasy', 4),
  ((SELECT id FROM projects WHERE slug='bilhetou'), 'images/work/bilhetou/01.webp', 'Bilhetou', 0),
  ((SELECT id FROM projects WHERE slug='bilhetou'), 'images/work/bilhetou/02.webp', 'Bilhetou', 1),
  ((SELECT id FROM projects WHERE slug='bilhetou'), 'images/work/bilhetou/03.webp', 'Bilhetou', 2),
  ((SELECT id FROM projects WHERE slug='bilhetou'), 'images/work/bilhetou/04.webp', 'Bilhetou', 3),
  ((SELECT id FROM projects WHERE slug='bilhetou'), 'images/work/bilhetou/05.webp', 'Bilhetou', 4),
  ((SELECT id FROM projects WHERE slug='atrai'), 'images/work/atrai/01.webp', 'Atrai', 0),
  ((SELECT id FROM projects WHERE slug='atrai'), 'images/work/atrai/02.webp', 'Atrai', 1),
  ((SELECT id FROM projects WHERE slug='atrai'), 'images/work/atrai/03.webp', 'Atrai', 2),
  ((SELECT id FROM projects WHERE slug='atrai'), 'images/work/atrai/04.webp', 'Atrai', 3),
  ((SELECT id FROM projects WHERE slug='atrai'), 'images/work/atrai/05.webp', 'Atrai', 4),
  ((SELECT id FROM projects WHERE slug='agil'), 'images/work/agil/01.webp', 'Ágil', 0),
  ((SELECT id FROM projects WHERE slug='agil'), 'images/work/agil/02.webp', 'Ágil', 1),
  ((SELECT id FROM projects WHERE slug='agil'), 'images/work/agil/03.webp', 'Ágil', 2),
  ((SELECT id FROM projects WHERE slug='agil'), 'images/work/agil/04.webp', 'Ágil', 3),
  ((SELECT id FROM projects WHERE slug='agil'), 'images/work/agil/05.webp', 'Ágil', 4),
  ((SELECT id FROM projects WHERE slug='spark'), 'images/work/spark/01.webp', 'Spark', 0),
  ((SELECT id FROM projects WHERE slug='spark'), 'images/work/spark/02.webp', 'Spark', 1),
  ((SELECT id FROM projects WHERE slug='spark'), 'images/work/spark/03.webp', 'Spark', 2),
  ((SELECT id FROM projects WHERE slug='spark'), 'images/work/spark/04.webp', 'Spark', 3),
  ((SELECT id FROM projects WHERE slug='spark'), 'images/work/spark/05.webp', 'Spark', 4),
  ((SELECT id FROM projects WHERE slug='evolve-sales'), 'images/work/evolve-sales/01.webp', 'Evolve Sales', 0),
  ((SELECT id FROM projects WHERE slug='evolve-sales'), 'images/work/evolve-sales/02.webp', 'Evolve Sales', 1),
  ((SELECT id FROM projects WHERE slug='evolve-sales'), 'images/work/evolve-sales/03.webp', 'Evolve Sales', 2),
  ((SELECT id FROM projects WHERE slug='evolve-sales'), 'images/work/evolve-sales/04.webp', 'Evolve Sales', 3),
  ((SELECT id FROM projects WHERE slug='evolve-sales'), 'images/work/evolve-sales/05.webp', 'Evolve Sales', 4),
  ((SELECT id FROM projects WHERE slug='carsure'), 'images/work/carsure/01.webp', 'Carsure', 0),
  ((SELECT id FROM projects WHERE slug='carsure'), 'images/work/carsure/02.webp', 'Carsure', 1),
  ((SELECT id FROM projects WHERE slug='carsure'), 'images/work/carsure/03.webp', 'Carsure', 2),
  ((SELECT id FROM projects WHERE slug='carsure'), 'images/work/carsure/04.webp', 'Carsure', 3),
  ((SELECT id FROM projects WHERE slug='carsure'), 'images/work/carsure/05.webp', 'Carsure', 4),
  ((SELECT id FROM projects WHERE slug='total-led'), 'images/work/total-led/01.webp', 'Total Led', 0),
  ((SELECT id FROM projects WHERE slug='total-led'), 'images/work/total-led/02.webp', 'Total Led', 1),
  ((SELECT id FROM projects WHERE slug='total-led'), 'images/work/total-led/03.webp', 'Total Led', 2),
  ((SELECT id FROM projects WHERE slug='total-led'), 'images/work/total-led/04.webp', 'Total Led', 3),
  ((SELECT id FROM projects WHERE slug='total-led'), 'images/work/total-led/05.webp', 'Total Led', 4),
  ((SELECT id FROM projects WHERE slug='gbs'), 'images/work/gbs/01.webp', 'GBS', 0),
  ((SELECT id FROM projects WHERE slug='gbs'), 'images/work/gbs/02.webp', 'GBS', 1),
  ((SELECT id FROM projects WHERE slug='gbs'), 'images/work/gbs/03.webp', 'GBS', 2),
  ((SELECT id FROM projects WHERE slug='gbs'), 'images/work/gbs/04.webp', 'GBS', 3),
  ((SELECT id FROM projects WHERE slug='gbs'), 'images/work/gbs/05.webp', 'GBS', 4),
  ((SELECT id FROM projects WHERE slug='vivamente'), 'images/work/vivamente/01.webp', 'Vivamente', 0),
  ((SELECT id FROM projects WHERE slug='vivamente'), 'images/work/vivamente/02.webp', 'Vivamente', 1),
  ((SELECT id FROM projects WHERE slug='vivamente'), 'images/work/vivamente/03.webp', 'Vivamente', 2),
  ((SELECT id FROM projects WHERE slug='vivamente'), 'images/work/vivamente/04.webp', 'Vivamente', 3),
  ((SELECT id FROM projects WHERE slug='vivamente'), 'images/work/vivamente/05.webp', 'Vivamente', 4),
  ((SELECT id FROM projects WHERE slug='dani-molino'), 'images/work/dani-molino/01.webp', 'Dani Molino', 0),
  ((SELECT id FROM projects WHERE slug='dani-molino'), 'images/work/dani-molino/02.webp', 'Dani Molino', 1),
  ((SELECT id FROM projects WHERE slug='dani-molino'), 'images/work/dani-molino/03.webp', 'Dani Molino', 2),
  ((SELECT id FROM projects WHERE slug='dani-molino'), 'images/work/dani-molino/04.webp', 'Dani Molino', 3),
  ((SELECT id FROM projects WHERE slug='dani-molino'), 'images/work/dani-molino/05.webp', 'Dani Molino', 4),
  ((SELECT id FROM projects WHERE slug='memorias-que-ficam'), 'images/work/memorias-que-ficam/01.webp', 'Memórias que Ficam', 0),
  ((SELECT id FROM projects WHERE slug='memorias-que-ficam'), 'images/work/memorias-que-ficam/02.webp', 'Memórias que Ficam', 1),
  ((SELECT id FROM projects WHERE slug='memorias-que-ficam'), 'images/work/memorias-que-ficam/03.webp', 'Memórias que Ficam', 2),
  ((SELECT id FROM projects WHERE slug='memorias-que-ficam'), 'images/work/memorias-que-ficam/04.webp', 'Memórias que Ficam', 3),
  ((SELECT id FROM projects WHERE slug='memorias-que-ficam'), 'images/work/memorias-que-ficam/05.webp', 'Memórias que Ficam', 4),
  ((SELECT id FROM projects WHERE slug='post-stenci'), 'images/work/post-stenci/01.webp', 'Post Stenci', 0),
  ((SELECT id FROM projects WHERE slug='post-stenci'), 'images/work/post-stenci/02.webp', 'Post Stenci', 1),
  ((SELECT id FROM projects WHERE slug='post-stenci'), 'images/work/post-stenci/03.webp', 'Post Stenci', 2),
  ((SELECT id FROM projects WHERE slug='post-stenci'), 'images/work/post-stenci/04.webp', 'Post Stenci', 3),
  ((SELECT id FROM projects WHERE slug='post-stenci'), 'images/work/post-stenci/05.webp', 'Post Stenci', 4),
  ((SELECT id FROM projects WHERE slug='applespace'), 'images/work/applespace/01.webp', 'AppleSpace', 0),
  ((SELECT id FROM projects WHERE slug='applespace'), 'images/work/applespace/02.webp', 'AppleSpace', 1),
  ((SELECT id FROM projects WHERE slug='applespace'), 'images/work/applespace/03.webp', 'AppleSpace', 2),
  ((SELECT id FROM projects WHERE slug='applespace'), 'images/work/applespace/04.webp', 'AppleSpace', 3),
  ((SELECT id FROM projects WHERE slug='applespace'), 'images/work/applespace/05.webp', 'AppleSpace', 4),
  ((SELECT id FROM projects WHERE slug='applespace'), 'images/work/applespace/06.webp', 'AppleSpace', 5),
  ((SELECT id FROM projects WHERE slug='lava-jato'), 'images/work/lava-jato/01.webp', 'Lava Jato', 0),
  ((SELECT id FROM projects WHERE slug='lava-jato'), 'images/work/lava-jato/02.webp', 'Lava Jato', 1),
  ((SELECT id FROM projects WHERE slug='lava-jato'), 'images/work/lava-jato/03.webp', 'Lava Jato', 2),
  ((SELECT id FROM projects WHERE slug='lava-jato'), 'images/work/lava-jato/04.webp', 'Lava Jato', 3),
  ((SELECT id FROM projects WHERE slug='lava-jato'), 'images/work/lava-jato/05.webp', 'Lava Jato', 4),
  ((SELECT id FROM projects WHERE slug='luz-casting'), 'images/work/luz-casting/01.webp', 'Luz Casting', 0),
  ((SELECT id FROM projects WHERE slug='luz-casting'), 'images/work/luz-casting/02.webp', 'Luz Casting', 1),
  ((SELECT id FROM projects WHERE slug='luz-casting'), 'images/work/luz-casting/03.webp', 'Luz Casting', 2),
  ((SELECT id FROM projects WHERE slug='luz-casting'), 'images/work/luz-casting/04.webp', 'Luz Casting', 3),
  ((SELECT id FROM projects WHERE slug='luz-casting'), 'images/work/luz-casting/05.webp', 'Luz Casting', 4),
  ((SELECT id FROM projects WHERE slug='jusp-2025'), 'images/work/jusp-2025/01.webp', 'JUSP 2025', 0),
  ((SELECT id FROM projects WHERE slug='jusp-2025'), 'images/work/jusp-2025/02.webp', 'JUSP 2025', 1),
  ((SELECT id FROM projects WHERE slug='jusp-2025'), 'images/work/jusp-2025/03.webp', 'JUSP 2025', 2),
  ((SELECT id FROM projects WHERE slug='jusp-2025'), 'images/work/jusp-2025/04.webp', 'JUSP 2025', 3),
  ((SELECT id FROM projects WHERE slug='jusp-2025'), 'images/work/jusp-2025/05.webp', 'JUSP 2025', 4),
  ((SELECT id FROM projects WHERE slug='shinkairace'), 'images/work/shinkairace/01.webp', 'Shinkai Race', 0),
  ((SELECT id FROM projects WHERE slug='shinkairace'), 'images/work/shinkairace/02.webp', 'Shinkai Race', 1),
  ((SELECT id FROM projects WHERE slug='shinkairace'), 'images/work/shinkairace/03.webp', 'Shinkai Race', 2),
  ((SELECT id FROM projects WHERE slug='shinkairace'), 'images/work/shinkairace/04.webp', 'Shinkai Race', 3),
  ((SELECT id FROM projects WHERE slug='shinkairace'), 'images/work/shinkairace/05.webp', 'Shinkai Race', 4),
  ((SELECT id FROM projects WHERE slug='twinkfighter'), 'images/work/twinkfighter/01.webp', 'Twinkfighter', 0),
  ((SELECT id FROM projects WHERE slug='twinkfighter'), 'images/work/twinkfighter/02.webp', 'Twinkfighter', 1),
  ((SELECT id FROM projects WHERE slug='twinkfighter'), 'images/work/twinkfighter/03.webp', 'Twinkfighter', 2),
  ((SELECT id FROM projects WHERE slug='twinkfighter'), 'images/work/twinkfighter/04.webp', 'Twinkfighter', 3),
  ((SELECT id FROM projects WHERE slug='twinkfighter'), 'images/work/twinkfighter/05.webp', 'Twinkfighter', 4),
  ((SELECT id FROM projects WHERE slug='star-games'), 'images/work/star-games/01.webp', 'Star Games', 0),
  ((SELECT id FROM projects WHERE slug='star-games'), 'images/work/star-games/02.webp', 'Star Games', 1),
  ((SELECT id FROM projects WHERE slug='star-games'), 'images/work/star-games/03.webp', 'Star Games', 2),
  ((SELECT id FROM projects WHERE slug='star-games'), 'images/work/star-games/04.webp', 'Star Games', 3),
  ((SELECT id FROM projects WHERE slug='star-games'), 'images/work/star-games/05.webp', 'Star Games', 4),
  ((SELECT id FROM projects WHERE slug='evo'), 'images/work/evo/01.webp', 'EVO', 0),
  ((SELECT id FROM projects WHERE slug='evo'), 'images/work/evo/02.webp', 'EVO', 1),
  ((SELECT id FROM projects WHERE slug='evo'), 'images/work/evo/03.webp', 'EVO', 2),
  ((SELECT id FROM projects WHERE slug='evo'), 'images/work/evo/04.webp', 'EVO', 3),
  ((SELECT id FROM projects WHERE slug='evo'), 'images/work/evo/05.webp', 'EVO', 4),
  ((SELECT id FROM projects WHERE slug='grp-city'), 'images/work/grp-city/01.webp', 'GRP City', 0),
  ((SELECT id FROM projects WHERE slug='grp-city'), 'images/work/grp-city/02.webp', 'GRP City', 1),
  ((SELECT id FROM projects WHERE slug='grp-city'), 'images/work/grp-city/03.webp', 'GRP City', 2),
  ((SELECT id FROM projects WHERE slug='grp-city'), 'images/work/grp-city/04.webp', 'GRP City', 3),
  ((SELECT id FROM projects WHERE slug='grp-city'), 'images/work/grp-city/05.webp', 'GRP City', 4),
  ((SELECT id FROM projects WHERE slug='baixada'), 'images/work/baixada/01.webp', 'Baixada', 0),
  ((SELECT id FROM projects WHERE slug='baixada'), 'images/work/baixada/02.webp', 'Baixada', 1),
  ((SELECT id FROM projects WHERE slug='baixada'), 'images/work/baixada/03.webp', 'Baixada', 2),
  ((SELECT id FROM projects WHERE slug='baixada'), 'images/work/baixada/04.webp', 'Baixada', 3),
  ((SELECT id FROM projects WHERE slug='baixada'), 'images/work/baixada/05.webp', 'Baixada', 4),
  ((SELECT id FROM projects WHERE slug='barra'), 'images/work/barra/01.webp', 'Barra', 0),
  ((SELECT id FROM projects WHERE slug='barra'), 'images/work/barra/02.webp', 'Barra', 1),
  ((SELECT id FROM projects WHERE slug='barra'), 'images/work/barra/03.webp', 'Barra', 2),
  ((SELECT id FROM projects WHERE slug='barra'), 'images/work/barra/04.webp', 'Barra', 3),
  ((SELECT id FROM projects WHERE slug='barra'), 'images/work/barra/05.webp', 'Barra', 4),
  ((SELECT id FROM projects WHERE slug='acalmarsi'), 'images/work/acalmarsi/01.webp', 'Acalmarsi', 0),
  ((SELECT id FROM projects WHERE slug='acalmarsi'), 'images/work/acalmarsi/02.webp', 'Acalmarsi', 1),
  ((SELECT id FROM projects WHERE slug='acalmarsi'), 'images/work/acalmarsi/03.webp', 'Acalmarsi', 2),
  ((SELECT id FROM projects WHERE slug='acalmarsi'), 'images/work/acalmarsi/04.webp', 'Acalmarsi', 3),
  ((SELECT id FROM projects WHERE slug='acalmarsi'), 'images/work/acalmarsi/05.webp', 'Acalmarsi', 4),
  ((SELECT id FROM projects WHERE slug='nova'), 'images/work/nova/01.webp', 'NOVA', 0),
  ((SELECT id FROM projects WHERE slug='nova'), 'images/work/nova/02.webp', 'NOVA', 1),
  ((SELECT id FROM projects WHERE slug='nova'), 'images/work/nova/03.webp', 'NOVA', 2),
  ((SELECT id FROM projects WHERE slug='nova'), 'images/work/nova/04.webp', 'NOVA', 3),
  ((SELECT id FROM projects WHERE slug='nova'), 'images/work/nova/05.webp', 'NOVA', 4),
  ((SELECT id FROM projects WHERE slug='pousada-maya'), 'images/work/pousada-maya/01.webp', 'Pousada Maya', 0),
  ((SELECT id FROM projects WHERE slug='pousada-maya'), 'images/work/pousada-maya/02.webp', 'Pousada Maya', 1),
  ((SELECT id FROM projects WHERE slug='pousada-maya'), 'images/work/pousada-maya/03.webp', 'Pousada Maya', 2),
  ((SELECT id FROM projects WHERE slug='pousada-maya'), 'images/work/pousada-maya/04.webp', 'Pousada Maya', 3),
  ((SELECT id FROM projects WHERE slug='pousada-maya'), 'images/work/pousada-maya/05.webp', 'Pousada Maya', 4),
  ((SELECT id FROM projects WHERE slug='pousada-maya'), 'images/work/pousada-maya/06.webp', 'Pousada Maya', 5),
  ((SELECT id FROM projects WHERE slug='pousada-maya'), 'images/work/pousada-maya/07.webp', 'Pousada Maya', 6),
  ((SELECT id FROM projects WHERE slug='pousada-maya'), 'images/work/pousada-maya/08.webp', 'Pousada Maya', 7),
  ((SELECT id FROM projects WHERE slug='pousada-maya'), 'images/work/pousada-maya/09.webp', 'Pousada Maya', 8),
  ((SELECT id FROM projects WHERE slug='pousada-maya'), 'images/work/pousada-maya/10.webp', 'Pousada Maya', 9),
  ((SELECT id FROM projects WHERE slug='lp-programmer'), 'images/work/lp-programmer/01.webp', 'LP Programmer', 0),
  ((SELECT id FROM projects WHERE slug='lp-programmer'), 'images/work/lp-programmer/02.webp', 'LP Programmer', 1),
  ((SELECT id FROM projects WHERE slug='lp-programmer'), 'images/work/lp-programmer/03.webp', 'LP Programmer', 2),
  ((SELECT id FROM projects WHERE slug='lp-programmer'), 'images/work/lp-programmer/04.webp', 'LP Programmer', 3),
  ((SELECT id FROM projects WHERE slug='lp-programmer'), 'images/work/lp-programmer/05.webp', 'LP Programmer', 4),
  ((SELECT id FROM projects WHERE slug='lp-programmer'), 'images/work/lp-programmer/06.webp', 'LP Programmer', 5),
  ((SELECT id FROM projects WHERE slug='lp-programmer'), 'images/work/lp-programmer/07.webp', 'LP Programmer', 6),
  ((SELECT id FROM projects WHERE slug='lp-programmer'), 'images/work/lp-programmer/08.webp', 'LP Programmer', 7),
  ((SELECT id FROM projects WHERE slug='lp-programmer'), 'images/work/lp-programmer/09.webp', 'LP Programmer', 8),
  ((SELECT id FROM projects WHERE slug='lp-programmer'), 'images/work/lp-programmer/10.webp', 'LP Programmer', 9);
